name: Haskell CI

on:
  push:
    branches: [ "main", "ci" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

steps: &cabal-test
- uses: actions/checkout@v4

- name: Cache Cabal
  id: cache-cabal
  uses: actions/cache@v4
  with:
    path: ~/.cabal
    key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
    restore-keys: |
      ${{ runner.os }}-build-${{ env.cache-name }}-
      ${{ runner.os }}-build-
      ${{ runner.os }}-

- name: Install dependencies
  run: |
    cabal update
    cabal build --only-dependencies --enable-tests --enable-benchmarks
- name: Build
  run: cabal build --enable-tests --enable-benchmarks all
- name: Test
  run: cabal test



jobs:

  build-982:
    runs-on: ubuntu-latest
    container:
      image: haskell:9.8.2
    steps: *cabal-test

  build-966:
    runs-on: ubuntu-latest
    container:
      image: haskell:9.6.6
    steps: *cabal-test


    # - uses: actions/setup-haskell@v1
    #   with:
    #     ghc-version: '9.6'
    #     cabal-version: '3.2'

    # - name: Cache
    #   uses: actions/cache@v3
    #   env:
    #     cache-name: cache-cabal
    #   with:
    #     path: ~/.cabal
    #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
    #     restore-keys: |
    #       ${{ runner.os }}-build-${{ env.cache-name }}-
    #       ${{ runner.os }}-build-
    #       ${{ runner.os }}-
