name: Haskell CI

on:
  push:
    branches: [ "main", "ci" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read



jobs:
  build-cache:
    runs-on: ubuntu-latest
    container:
      image: haskell:9.8.2
    steps: 
      - uses: actions/checkout@v4

      - name: Cache Cabal
        id: cache-cabal
        uses: actions/cache@v4
        with:
          path: |
            /github/home/.cache
            /github/home/.config
            /github/home/.local
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/cabal.project') }}-${{ hashFiles('**/*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          cabal update

      - name: Build dependencies
        run: |
          cabal build --only-dependencies --enable-tests --enable-benchmarks

      - name: Install skeletest-preprocessor
        run: |
          cabal install skeletest --installdir=$HOME/.local/bin --install-method=copy
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Check Cache
        run: |
          ls -ahl /github/home/
          ls -ahl /github/home/.cache
          ls -ahl /github/home/.config
          ls -ahl /github/home/.local

  build-982:
    needs: build-cache
    runs-on: ubuntu-latest
    container:
      image: haskell:9.8.2
    steps: 
      - uses: actions/checkout@v4

      - name: Cache Cabal Restore
        id: cache-cabal-restore
        uses: actions/cache@v4
        with:
          path: |
            /github/home/.cache
            /github/home/.config
            /github/home/.local
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/cabal.project') }}-${{ hashFiles('**/*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Check Cache
        run: |
          ls -ahl /github/home/
          ls -ahl /github/home/.cache
          ls -ahl /github/home/.config
          ls -ahl /github/home/.local

      - name: Install skeletest-preprocessor
        run: |
          cabal install skeletest --installdir=$HOME/.local/bin --install-method=copy
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build
        run: cabal build --enable-tests --enable-benchmarks all

      - name: Test
        run: cabal test

  # build-966:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: haskell:9.6.6
  #   steps: *cabal-test


    # - uses: actions/setup-haskell@v1
    #   with:
    #     ghc-version: '9.6'
    #     cabal-version: '3.2'

    # - name: Cache
    #   uses: actions/cache@v3
    #   env:
    #     cache-name: cache-cabal
    #   with:
    #     path: ~/.cabal
    #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
    #     restore-keys: |
    #       ${{ runner.os }}-build-${{ env.cache-name }}-
    #       ${{ runner.os }}-build-
    #       ${{ runner.os }}-
